# Nazwa całego procesu automatyzacji
name: Codzienne generowanie raportu dla dane.gov.pl

on:
  schedule:
    - cron: '1 23 * * *'
  workflow_dispatch:

permissions:
  contents: read
  # UPRAWNIENIA KLUCZOWE DLA NOWEJ METODY:
  # Nadaje uprawnienia do tworzenia i publikowania strony GitHub Pages
  pages: write
  id-token: write

jobs:
  # Zadanie 1: Generowanie plików
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script to generate XML and MD5
        run: python generator_danych_gov.py

      - name: Prepare daily data file
        run: |
          INWESTYCJA_ID=$(python -c "from generator_danych_gov import CONFIG; print(CONFIG['INWESTYCJA_ID'])")
          TODAY_STR=$(date +'%Y-%m-%d')
          cp dane_wzor.xlsx "ceny-${INWESTYCJA_ID}-${TODAY_STR}.xlsx"
      
      # KROK KLUCZOWY: Zamiast publikować, pakujemy pliki do "artefaktu"
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2
        with:
          # Ścieżka, z której pakujemy pliki (w naszym przypadku główny katalog)
          path: .

  # Zadanie 2: Publikacja strony z "artefaktu"
  deploy:
    # To zadanie jest zależne od pomyślnego ukończenia zadania 'build'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # KROK KLUCZOWY: Użycie oficjalnej akcji do publikacji z artefaktu
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
