# Nazwa całego procesu automatyzacji, widoczna w zakładce "Actions" na GitHub
name: Codzienne generowanie raportu dla dane.gov.pl

# Sekcja definiująca, kiedy proces ma być uruchamiany
on:
  schedule:
    - cron: '1 23 * * *'
  workflow_dispatch:

# --- POPRAWKA: Nadanie uprawnień do zapisu ---
# Ta sekcja jest kluczowa. Nadaje ona automatowi uprawnienia do zapisu ("write")
# w repozytorium, co jest niezbędne do publikacji plików na GitHub Pages.
permissions:
  contents: write
# ---------------------------------------------

# Definicja zadań do wykonania
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script to generate XML and MD5
        run: python generator_danych_gov.py

      - name: Prepare daily data file
        run: |
          INWESTYCJA_ID=$(python -c "from generator_danych_gov import CONFIG; print(CONFIG['INWESTYCJA_ID'])")
          TODAY_STR=$(date +'%Y-%m-%d')
          cp dane_wzor.xlsx "ceny-${INWESTYCJA_ID}-${TODAY_STR}.xlsx"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,*.py,dane_wzor.xlsx'
